### ISSUE TITLE
ROS2 release

### ISSUE THREAD

**Issue by tylerjw** [UniversalRobots/Universal_Robots_ROS_Driver#253]
# Summary

Please release a ROS2 version targeting the rolling release of Foxy of this driver so we and others can use our UR5 with ROS2.

**Comment by davetcoleman** [comment]
Duplicate of https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/69

Summary from @gavanderhoorn :
>Porting the driver (so not the library) to ROS 2 is complicated right now because of the lack of ros_control support in ROS 2.


btw I started a discussion on ROS 2 support for the [old ur_modern_driver repo here](https://github.com/ros-industrial/ur_modern_driver/issues/244). It was closed because that repo is depricated.

**Comment by tylerjw** [comment]
Closing in favor of the older issue.
