### ISSUE TITLE
How can I add gripper on UR

### ISSUE THREAD

**Issue by ChangcongWang** [UniversalRobots/Universal_Robots_ROS_Driver#375]
Hello,

I try to add robotiq_85_gripper to my ur robot. 

But every time I use `roslaunch ur_robor_driver` the tf tree is broken.

And **I only add the following code to `ur5_robot.urdf.xacro`. Should I add any other  thing to somewhere?**
```
  <!-- robotiq 85 -->
  <xacro:include filename="$(find robotiq_85_description)/urdf/robotiq_85_gripper.urdf.xacro" />

  <!-- gripper -->
  <xacro:robotiq_85_gripper prefix="" parent="ee_link" >
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper>
```

## Expected Behavior
Using roslanch display.launch I can get the right tf tree. The following is display.launch.
```
<launch>
  <include file="$(find robotiq_85_description)/launch/upload_robotiq_85_gripper1.launch"/>
  <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
  <node name="robot_state_publisher" pkg="robot_state_publisher" type="state_publisher" />
</launch>
```
It can get the right tf tree.
<a href="https://sm.ms/image/Ixrb9hEWaD651wi" target="_blank"><img src="https://i.loli.net/2021/05/13/Ixrb9hEWaD651wi.png" ></a>

## Actual Behavior
The following is the tf tree using `roslaunch ur_robor_driver`.
<a href="https://sm.ms/image/HK6VjYFAnWa4RPc" target="_blank"><img src="https://i.loli.net/2021/05/13/HK6VjYFAnWa4RPc.png" ></a>

**Comment by fmauch** [comment]
The description is not really a part of this repository. The launchfiles only contain a flag to launch another description if desired.

This being said, try to generate **a new** xacro file  (preferably inside a package describing your particular workcell / application) containing both, the robot and the gripper. In a test `display.launch` file you should then load the xacro file of the **combined** description. As soon as this works, you should be able to create a launchfile loading that description and passing that to the bringup launchfile of this driver.

As this issue is not really concerning this repository, I'm going to close this. If you keep having trouble creating your combined description, the best place to ask for assistance would be ROS answers. Please mention this issue if you post a new question about this on ROS answers, so we can keep track how everything is being connected to each other.
