### ISSUE TITLE
roslaunch ur_robot_driver ur3_bringup.launch error

### ISSUE THREAD

**Issue by seunghwa9118** [UniversalRobots/Universal_Robots_ROS_Driver#386]
# Summary
I write on terminal ur_robot_driver ur3_bringup.launch robot_ip:=192.168.100.1 but i got an error
How can i fix it?
# Versions
 - ROS Driver version: 16.04ubuntu + kinetic
![스크린샷, 2021-05-25 13-20-07](https://user-images.githubusercontent.com/68892551/119438911-38a65d80-bd5c-11eb-8c25-28ca65942104.png)

**Comment by fmauch** [comment]
Please use [code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead of screenshots to attach terminal output.

Did you make sure that your full workspace is up-to date? #97 was merged, an updated `ur_description` (`git pull` inside the `universal_robot` package) is needed.

**Comment by stefanscherzinger** [comment]
@seunghwa9118 Is this still an issue after applying @fmauch 's suggestions?

**Comment by stefanscherzinger** [comment]
Feel free to re-open if this issue persists.
