### ISSUE TITLE
Getting the current robot position without an active controller?

### ISSUE THREAD

**Issue by AlcatrAAz** [UniversalRobots/Universal_Robots_ROS_Driver#435]
# Question

Hello

Is it possible with the (latest) UR ROS Driver to get the current position of the Robot in a ROS topic (without an active Controller)? I use the latest UR ROS Driver and the new cartesian controllers (pass through controller) and at the moment I do a workaround where I send a goal with a very long time_duration and with the first feedback that I get from the Ros Action I immediately cancel the goal. It works, but it isn't really nice... :)

**Comment by fmauch** [comment]
With "Position of the robot" I assume, you mean the robot's TCP pose?

all robot links are published using the built-in tf system. So, in order to use the robot's tcp pose (which is the frame `tool0` by default), utilize a [`tf_listener`](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29) inside your node consuming it.

If you absolutely require it to be published on a ROS topic, you can easily write a small node that contains a `tf_listener` and a publisher publishing the looked-up transformation yourself. Probably, there already exists something like that, already.

As I think that your question has been answered, I'll go ahead and close this issue. Feel free to comment or reopen, if you think that there is anything missing.
