### ISSUE TITLE
isolate / release controller_stopper

### ISSUE THREAD

**Issue by v4hn** [UniversalRobots/Universal_Robots_ROS_Driver#523]
The controller_stopper package is useful standalone, also if no UR arms are involved.

shadow-robot, possibly among others use the package with their own ros_control-powered hardware and we actually [forked this repository](https://github.com/TAMS-Group/Universal_Robots_ROS_Driver/commits/controller_stopper_only) just to get this small helper node without pulling in UR.
It would be great if you could either (1) split the package into a small separate repository or (2) release it into ROS noetic, so we don't have to compile it ourselves.

**Comment by fmauch** [comment]
Indeed that it was the plan initially to make it also available for others, hence the standalone package. Back then I didn't anticipate that getting a binary release would take such a long time. I'd still like to push that forward rather than investing time splitting this single package, but I definitively understand your concerns.

However, please note that we are currently very busy making the first ROS2 binary release and after that, some focus will definitively go into updating [ros-industrial/universal_robot](https://github.com/ros-industrial/universal_robot) and therefore moving towards a binary release for this repo.

**Comment by v4hn** [comment]
I'm not at all happy with the solution to move it [even further into ur_robot_driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/609) instead of splitting it up, but apparently someone vetoed the package name...
Where is the link to that discussion by the way? I can't seem to find it in rosdistro.

I'll close this as "No Fix" for now.

**Comment by gavanderhoorn** [comment]
https://github.com/ros/rosdistro/pull/35593#discussion_r1044750091
