### ISSUE TITLE
How to use the ROSTOPIC as a variable in main function of python?

### ISSUE THREAD

**Issue by ZZWang21** [UniversalRobots/Universal_Robots_ROS_Driver#564]
I am planning to control the position of the robotic arm according to the contact force.

I can achieve the force signal from Rostopic. The frequency of the data is quite high.

Now I want to write a python code to control the z position of the end-effector according to the force. However, I can subscribe to the topic, I can print the force value in terminal, but I do not know how to use the force value in the main functions, such as if function.

My target is to set a "if" function, if the force is over 10 N, z position -0.1.

Anybody could help? Thank you very much.

**Comment by fmauch** [comment]
This is not really a question regarding this driver, that's why I'll close it as invalid. Such application-based questions are better asked on ROS answers.

However, that being said, to give you a hint:

- write a node that subscribes to the robot's wrench
- In the callback of that wrench, check your condition
- If your condition hits, publish a command to the robot (e.g. publish a message to the trajectory controller's command topic)

If I understand correctly, this should help you implementing what you asked for.
