### ISSUE TITLE
Changing Twist controller reference frame from Base to TCP frame

### ISSUE THREAD

**Issue by MCR100** [UniversalRobots/Universal_Robots_ROS_Driver#644]
I need some help to change the robot’s jogging reference frame of “twist_controller”. We are trying to implement some robot application based on “Universal_robot_ROS_driver”.

We are using a UR5e robot with ROS noetic on Ubuntu 20.04.
I switched the ROS controller manager to “twist_controller” and used the input topic “Geometry_msgs/Twist” type to control the TCP’s linear and angular velocities. When executing the commands, the robot’s TCP  uses Base as a reference frame to jog, but we are looking to jog the robot around TCP frame.
Any ways to change the reference frame from Base to TCP for twist controller?

Thank you in advance.

**Comment by fmauch** [comment]
Changing the reference frame is not supported and will probably not be implemented for ROS1 anymore.  If you'd like to command in TCP frame, then you would have to write a small wrapper node that does the transformation for you. Or you could modify https://github.com/UniversalRobots/Universal_Robots_ROS_controllers_cartesian/tree/main/twist_controller and create a Pull Request there. 

Since the twist_controller doesn't live inside this repo, I'll go ahead and close this issue. If you'd like to add twist transformation to the twist_controller, please open a PR / issue at its repository.
