### ISSUE TITLE
URDF not updating with frames

### ISSUE THREAD

**Issue by martamillet** [UniversalRobots/Universal_Robots_ROS_Driver#9]
# Summary

I am trying the driver with a real UR10 and if I launch it and open rviz I am not able to see the robot model in its real position. The frames on the other hand, are properly placed in position and the topic of the joint states publishes the correct positions. 
I am also able to move the robot with the rqt_joint_trajectory_controller.

I've tried it with two different UR10 and I got the same result.

# Versions
 - ROS Driver version: ros kinetic
 - Affected Robot Software Version(s):  3.7.040195
 - Robot Serial Number:2018309743
 - UR+ product(s) installed: none
 - URCaps Software version(s): 1.0.1

# Impact
Apparently it is just the visualization of the URDF model that isn't correct but we won't be able to use moveit this way.

# Issue details
I install the URCap as specified in the ReadMe file and launch it.
In the ros connected machine I run the calibration command 
$ roslaunch ur_calibration calibration_correction.launch \
robot_ip:=192.168.0.210 target_filename:="${HOME}/my_robot_calibration.yaml"

And then 

roslaunch ur_robot_driver ur10_bringup.launch robot_ip:=192.168.0.210
    kinematics_config:="${HOME}/my_robot_calibration.yaml"

And get the connection with the robot when executing the program in the UR with the external control block.
I am able to move the robot with the trajectory  controller, read properly the joint states, the frames are in the real position but the URDF model of the arm stays in position o.
## Use Case and Setup
We are trying to update all our robots with the new driver and test it in different ways.

## Project status at point of discovered
*When did you first observe the issue?*
I observed the issue when opening RVIZ

## Expected Behavior
I expected the URDF model of the arm to  be updated with the real position

## Actual Behavior
URDF model of the arm stays in the zero position. I attach a screenshot.
![issue_UR_driver](https://user-images.githubusercontent.com/36037891/67074755-06994680-f18a-11e9-82c1-365be6239607.png)

## Workaround Suggestion
*If a workaround has been found, you are welcome to share.*

**Comment by fmauch** [comment]
The RViz plugin `RobotState` is actually a MoveIt! plugin, so you probably need to start some MoveIt! component to use it. I am myself not too familiar with MoveIt!, so I can't give you a proper hint here. If you want to see the robot model as a rendered version of the URDF filled with live robot data (joint states), use the `RobotModel` RViz plugin instead.

So, in my eyes this is a wontfix, as it is not an issue of the driver but of using some 3rdparty tools. If you agree, please close the issue, otherwise please let me know how we can further help you from a driver's perspective.
